{
 "title": "Outline",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Are users using the service?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Access Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(increase(shadowsocks_data_bytes{access_key!=\"\"} [1h])) by (access_key, location) > bool 0) by (location)",
     "legendFormat": "1h {{location}}"
    },
    {
     "expr": "sum(max(max_over_time(shadowsocks_data_bytes{access_key!=\"\"} [1d])) by (access_key) > bool 0)",
     "legendFormat": "1d"
    },
    {
     "expr": "sum(max(max_over_time(shadowsocks_data_bytes{access_key!=\"\"} [7d])) by (access_key) > bool 0)",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Access Key 1h Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(shadowsocks_data_bytes[1h])) by (access_key)",
     "legendFormat": "{{access_key}}"
    }
   ]
  },
  {
   "title": "Total Data usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shadowsocks_data_bytes{dir=~\"c<p|p>t\"} [1h])) by (location)",
     "legendFormat": "1h {{location}}"
    },
    {
     "expr": "sum(increase(shadowsocks_data_bytes{dir=~\"c<p|p>t\"} [1d]))",
     "legendFormat": "1d"
    },
    {
     "expr": "sum(increase(shadowsocks_data_bytes{dir=~\"c<p|p>t\"} [7d]))",
     "legendFormat": "7d"
    },
    {
     "expr": "sum(increase(shadowsocks_data_bytes{dir=~\"c<p|p>t\"} [4w]))",
     "legendFormat": "4w"
    }
   ]
  },
  { "title": "Is the service healthy?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"outline\"}[10m])",
     "legendFormat": "cpu {{job}}"
    },
    {
     "expr": "go_goroutines{job=\"outline\"}",
     "legendFormat": "go_goroutines {{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"outline\"}",
     "legendFormat": "virtual_memory {{job}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shadowsocks_tcp_connection_duration_ms_count [10m])) by (access_key, status)",
     "legendFormat": "count/s {{access_key}} {{status}}"
    },
    {
     "expr": "sum(rate(shadowsocks_tcp_connection_duration_ms_sum [10m])) by (access_key,status) / sum(rate(shadowsocks_tcp_connection_duration_ms_count [10m])) by (access_key, status)",
     "legendFormat": "duration {{access_key}} {{status}}"
    }
   ]
  },
  {
   "title": "Open TCP Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(shadowsocks_tcp_connections_opened) -  sum(shadowsocks_tcp_connections_closed)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shadowsocks_tcp_connections_closed{status=~\"ERR_.*\"} [10m])) by (status, access_key)",
     "legendFormat": "{{status}} {{access_key}}"
    }
   ]
  },
  {
   "title": "Total Access Keys",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "shadowsocks_keys" }
   ]
  },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 25 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"outline\"}"
    }
   ]
  }
 ]
}